# Generated by Django 2.2 on 2020-08-04 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='brands_logo', verbose_name='логотип')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='имя категории')),
                ('description', models.TextField(blank=True, verbose_name='описание категории')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='category_images', verbose_name='фото категории')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='имя подкатегории')),
                ('description', models.TextField(blank=True, verbose_name='описание подкатегории')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='category_images', verbose_name='фото категории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='mainapp.ProductCategory', verbose_name='категория продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='имя продукта')),
                ('image', models.ImageField(blank=True, upload_to='products_images')),
                ('short_desc', models.CharField(blank=True, max_length=64, verbose_name='краткое описание')),
                ('desc', models.TextField(blank=True, verbose_name='описание товара')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена продукта')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена со скидкой')),
                ('quantity', models.PositiveIntegerField(default=10, verbose_name='количество на складе')),
                ('color', models.CharField(blank=True, max_length=32, verbose_name='цвет')),
                ('is_active', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('мужской', 'M'), ('женский', 'W')], default='мужской', max_length=1, verbose_name='пол')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mainapp.ProductBrand', verbose_name='бренд продукта')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mainapp.ProductSubCategory', verbose_name='подкатегория продукта')),
            ],
        ),
    ]
