# Generated by Django 2.2 on 2020-08-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('мужской', 'M'), ('женский', 'W')], default='мужской', max_length=15, verbose_name='пол'),
        ),
    ]
