# Generated by Django 2.2 on 2020-08-17 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200804_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_products', to='mainapp.ProductBrand', verbose_name='бренд продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc_products', to='mainapp.ProductSubCategory', verbose_name='подкатегория продукта'),
        ),
    ]
